apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roombook-api
  title: RoomBook API
  description: Sistema de reservas desarrollado con Spring Boot
  tags:
    - java
    - spring-boot
    - docker
    - postgresql
    - prometheus
    - grafana
    - loki

  annotations:
    github.com/project-slug: carlos-navarro-dev-fullstack/Sistema_Reservas_Backend
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: roombook

spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: roombook